<?php
// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `xgd_iceintf_base.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once('Ice.php');

if(!isset($core__t_SlcAttrsMap))
{
    $core__t_SlcAttrsMap = IcePHP_defineDictionary('::core::SlcAttrsMap', $IcePHP__t_string, $IcePHP__t_string);
}

if(!class_exists('core_SrvMsgHeader'))
{
    class core_SrvMsgHeader
    {
        public function __construct($DestServiceID=0, $MessageID='', $MsgType=0, $RequestID='', $SrcServiceID=0, $SrcSapID='', $Result=0, $DestSapID='', $Version='', $NeedCallBack=0, $RespMsgID='', $timeout=0, $ExtendParam=null)
        {
            $this->DestServiceID = $DestServiceID;
            $this->MessageID = $MessageID;
            $this->MsgType = $MsgType;
            $this->RequestID = $RequestID;
            $this->SrcServiceID = $SrcServiceID;
            $this->SrcSapID = $SrcSapID;
            $this->Result = $Result;
            $this->DestSapID = $DestSapID;
            $this->Version = $Version;
            $this->NeedCallBack = $NeedCallBack;
            $this->RespMsgID = $RespMsgID;
            $this->timeout = $timeout;
            $this->ExtendParam = $ExtendParam;
        }

        public function __toString()
        {
            global $core__t_SrvMsgHeader;
            return IcePHP_stringify($this, $core__t_SrvMsgHeader);
        }
		

        public $DestServiceID;
        public $MessageID;
        public $MsgType;
        public $RequestID;
        public $SrcServiceID;
        public $SrcSapID;
        public $Result;
        public $DestSapID;
        public $Version;
        public $NeedCallBack;
        public $RespMsgID;
        public $timeout;
        public $ExtendParam;
    }

    $core__t_SrvMsgHeader = IcePHP_defineStruct('::core::SrvMsgHeader', 'core_SrvMsgHeader', array(
        array('DestServiceID', $IcePHP__t_int), 
        array('MessageID', $IcePHP__t_string), 
        array('MsgType', $IcePHP__t_int), 
        array('RequestID', $IcePHP__t_string), 
        array('SrcServiceID', $IcePHP__t_int), 
        array('SrcSapID', $IcePHP__t_string), 
        array('Result', $IcePHP__t_int), 
        array('DestSapID', $IcePHP__t_string), 
        array('Version', $IcePHP__t_string), 
        array('NeedCallBack', $IcePHP__t_int), 
        array('RespMsgID', $IcePHP__t_string), 
        array('timeout', $IcePHP__t_int), 
        array('ExtendParam', $core__t_SlcAttrsMap)));
}

if(!isset($core__t_SrvMsgContent))
{
    $core__t_SrvMsgContent = IcePHP_defineSequence('::core::SrvMsgContent', $IcePHP__t_byte);
}

if(!interface_exists('core_ServerSap'))
{
    interface core_ServerSap
    {
        public function InvokeBinAsync($header, $request);
        public function InvokeBinSync($header, $request, $response);
        public function InvokeTxtAsync($header, $request);
        public function InvokeTxtSync($header, $request, $response);
        public function InvokeOamAsync($ServiceID, $MessageID, $request);
        public function InvokeOamSync($ServiceID, $MessageID, $request, $response);
    }

    class core_ServerSapPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::core::ServerSap', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::core::ServerSap', $facet);
        }
    }

    $core__t_ServerSap = IcePHP_defineClass('::core::ServerSap', 'core_ServerSap', -1, true, false, $Ice__t_Object, null, null);

    $core__t_ServerSapPrx = IcePHP_defineProxy($core__t_ServerSap);

    IcePHP_defineOperation($core__t_ServerSap, 'InvokeBinAsync', 0, 0, 0, array(array($core__t_SrvMsgHeader, false, 0), array($core__t_SrvMsgContent, false, 0)), null, array($IcePHP__t_int, false, 0), null);
    IcePHP_defineOperation($core__t_ServerSap, 'InvokeBinSync', 0, 0, 0, array(array($core__t_SrvMsgHeader, false, 0), array($core__t_SrvMsgContent, false, 0)), array(array($core__t_SrvMsgContent, false, 0)), array($IcePHP__t_int, false, 0), null);
    IcePHP_defineOperation($core__t_ServerSap, 'InvokeTxtAsync', 0, 0, 0, array(array($core__t_SrvMsgHeader, false, 0), array($IcePHP__t_string, false, 0)), null, array($IcePHP__t_int, false, 0), null);
    IcePHP_defineOperation($core__t_ServerSap, 'InvokeTxtSync', 0, 0, 0, array(array($core__t_SrvMsgHeader, false, 0), array($IcePHP__t_string, false, 0)), array(array($IcePHP__t_string, false, 0)), array($IcePHP__t_int, false, 0), null);
    IcePHP_defineOperation($core__t_ServerSap, 'InvokeOamAsync', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($IcePHP__t_int, false, 0), null);
    IcePHP_defineOperation($core__t_ServerSap, 'InvokeOamSync', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), array(array($IcePHP__t_string, false, 0)), array($IcePHP__t_int, false, 0), null);

}
?>
